name: Post welcome comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo PR: ${{ github.event.issue.pull_request }} 
          echo body: ${{ github.event.comment.body }}
          echo pr number: ${{ github.event.issue.number }}
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo PR: ${{ github.event.issue.pull_request }} 
          echo body: ${{ github.event.comment.body }}
