name: Post welcome comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: User specified ${{ github.event.comment.body }}
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'test ') && github.event.issue.pull_request.head.repo.full_name == github.event.issue.pull_request.base.repo.full_name
    runs-on: ubuntu-latest

    steps:
      - name: Get test name from comment
        run: |
          echo "selected_it_test=$(echo "${{ github.event.comment.body }}" | cut -d ' ' -f 2 | xargs echo)" >> $GITHUB_ENV

      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.issue.pull_request.head.repo.full_name }}
          ref: ${{ github.event.issue.pull_request.head.ref }}

      - uses: octokit/request-action@v2.x
        name: Create check
        id: create_check_run
        with:
          route: POST /repos/${{ github.event.issue.pull_request.head.repo.full_name }}/check-runs
          name: ${{ github.event.comment.body }}
          head_sha: ${{ github.event.issue.pull_request.head.sha }}
          status: in_progress
          output: | # The | is significant!
            title: Custom tests
            summary: User specified integration ${{ github.event.comment.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: octokit/request-action@v2.x
        name: Complete check
        id: complete_check_run
        with:
          route: POST /repos/${{ github.event.issue.pull_request.head.repo.full_name }}/check-runs
          name: ${{ github.event.comment.body }}
          head_sha: ${{ github.event.issue.pull_request.head.sha }}
          status: ${{ job.status }}
          output: | # The | is significant!
            title: Custom tests
            summary: User specified integration ${{ github.event.comment.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
