name: Post welcome comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: User specified ${{ github.event.comment.body }}
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'test ')
    runs-on: ubuntu-latest

    steps:
      - name: Get test name from comment
        run: |
          echo "selected_it_test=$(echo "${{ github.event.comment.body }}" | cut -d ' ' -f 2 | xargs echo)" >> $GITHUB_ENV
          echo "${{ toJson(github.event) }}"

      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse PR information
        id: pr_data
        run: |
          echo "::set-output name=branch::${{ fromJson(steps.request.outputs.data).head.ref }}"
          echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).head.repo.full_name }}"
          echo "::set-output name=sha::${{ fromJson(steps.request.outputs.data).head.sha }}"

      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ steps.pr_data.outputs.repo_name }}
          ref: ${{ steps.pr_data.outputs.branch }}

      - uses: octokit/request-action@v2.x
        name: Create check
        id: create_check_run
        with:
          route: POST /repos/${{ steps.pr_data.outputs.repo_name }}/check-runs
          name: ${{ github.event.comment.body }}
          head_sha: ${{ steps.pr_data.outputs.sha }}
          status: in_progress
          output: | # The | is significant!
            title: Custom tests
            summary: User specified integration ${{ github.event.comment.body }} ([details](https://github.com/${{ steps.pr_data.outputs.repo_name }}/actions/runs/${{ github.run_id }}))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: octokit/request-action@v2.x
        name: Complete check
        id: complete_check_run
        with:
          route: POST /repos/${{ steps.pr_data.outputs.repo_name }}/check-runs
          name: ${{ github.event.comment.body }}
          head_sha: ${{ steps.pr_data.outputs.sha }}
          status: completed
          conclusion: ${{ job.status }}
          output: | # The | is significant!
            title: Custom tests
            summary: User specified integration ${{ github.event.comment.body }} ([details](https://github.com/${{ steps.pr_data.outputs.repo_name }}/actions/runs/${{ github.run_id }}))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
